#!/usr/bin/env python3
"""Optionally build legacy master_TASK.prompt files from base + contracts.

Normal runs no longer need these generated files: --prompt-dir myprompts is
composed at runtime from _unified_crossvid_base.prompt and task_contracts/*.prompt.
Keep this script only for older code paths that still expect physical
master_TASK.prompt files.
"""

import os


HERE = os.path.dirname(os.path.abspath(__file__))
BASE_FILE = os.path.join(HERE, "_unified_crossvid_base.prompt")
CONTRACT_DIR = os.path.join(HERE, "task_contracts")
TASKS = ["BU", "CC", "CCQA", "FSA", "MOC", "MSR", "NC", "PEA", "PI", "PSS"]


def read_text(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read().strip()


def main():
    base = read_text(BASE_FILE)
    header = (
        "<!-- Auto-generated by myprompts/build_unified_prompts.py. "
        "Edit _unified_crossvid_base.prompt or task_contracts/*.prompt, then rebuild. -->"
    )
    for task in TASKS:
        contract_path = os.path.join(CONTRACT_DIR, task + ".prompt")
        contract = read_text(contract_path)
        out_path = os.path.join(HERE, "master_" + task + ".prompt")
        text = header + "\n\n" + base + "\n\n" + contract + "\n"
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote", out_path)


if __name__ == "__main__":
    main()
